PIR_GPIO = 24
DHT_GPIO_PIN = 4
RAIN_CHANNEL = 0

SPI_BUS = 0
SPI_DEVICE = 0
SPI_MAX_SPEED_HZ = 1350000

DASHBOARD_IP = "192.168.50.103"   # change this to your device ip address
DASHBOARD_PORT = 8000
DASHBOARD_API_URL = f"http://{DASHBOARD_IP}:{DASHBOARD_PORT}/api/sensor-update"

SEND_INTERVAL_SEC = 3
REQUEST_TIMEOUT_SEC = 3

RAIN_NO_RAIN_THRESHOLD = 660
RAIN_LIGHT_RAIN_THRESHOLD = 490
