const profiles = {
  general: { label: "Computer Engineering Portfolio", title: "Engineering projects built across software and systems.", copy: "A balanced portfolio covering software development, databases, networking, operating systems, embedded systems and personal product work.", skills: ["Python","JavaScript","C/C++","SQL","Node.js","Databases","Networking","Embedded Systems"], featured: ["trading","tourism","embedded"], order: ["trading","tourism","chatbot","hobby","embedded","os","network","dsa"], note: "A broad selection showing experience across both software and system-level engineering." },
  software: { label: "Software Engineering Portfolio", title: "Software projects focused on building usable applications.", copy: "Selected projects emphasizing application development, APIs, databases, software architecture and practical development experience.", skills: ["Python","JavaScript","Node.js","APIs","SQL","Databases","Full Stack"], featured: ["trading","tourism","chatbot"], order: ["trading","tourism","chatbot","hobby","dsa","network","os","embedded"], note: "Software-focused projects are prioritized while systems projects remain available for technical breadth." },
  backend: { label: "Backend Engineering Portfolio", title: "Backend and data-focused projects built around services and persistence.", copy: "Projects emphasizing backend logic, APIs, relational and NoSQL databases, data handling and application architecture.", skills: ["Node.js","Python","MySQL","Firestore","SQLite","APIs","Backend Architecture"], featured: ["trading","tourism","chatbot"], order: ["trading","tourism","chatbot","dsa","os","network","hobby","embedded"], note: "Projects involving backend logic, databases and data processing appear first." },
  frontend: { label: "Frontend Engineering Portfolio", title: "Frontend projects focused on interaction, usability and product experience.", copy: "Selected work emphasizing web interfaces, user-facing workflows, JavaScript and responsive frontend development.", skills: ["JavaScript","Frontend","Responsive UI","UX","Web Applications"], featured: ["hobby","tourism","trading"], order: ["hobby","tourism","trading","chatbot","dsa","network","os","embedded"], note: "User-facing and web projects are prioritized for frontend applications." },
  embedded: { label: "Embedded & Systems Engineering Portfolio", title: "Systems projects focused on constrained environments and integration.", copy: "Selected projects emphasizing embedded development, operating systems, networking and system-level problem solving.", skills: ["Embedded Systems","Operating Systems","Networking","IoT","C/C++","System Integration"], featured: ["embedded","os","network"], order: ["embedded","os","network","dsa","chatbot","tourism","trading","hobby"], note: "Embedded, operating-system and networking projects are emphasized." },
  robotics: { label: "Robotics & Systems Portfolio", title: "Engineering projects relevant to robotics and autonomous systems.", copy: "Projects emphasizing embedded systems, networking, algorithms and system integration that provide a foundation for robotics engineering.", skills: ["Embedded Systems","Networking","Algorithms","Python","C/C++","System Integration"], featured: ["embedded","network","dsa"], order: ["embedded","network","dsa","os","chatbot","tourism","trading","hobby"], note: "Systems and algorithmic projects are prioritized for robotics-related applications." }
};
function getCurrentRole(){const p=new URLSearchParams(window.location.search);const r=(p.get("role")||"general").toLowerCase();return profiles[r]?r:"general";}
function createTags(skills){return skills.map(s=>`<span class="tag">${s}</span>`).join("");}
function createProjectCard(id){const p=projects[id];const v=p.video?`<span class="video-badge">▶ Video Demo</span>`:"";return `<article class="project-card featured"><div class="project-meta"><span>${p.type}</span><span class="status">${p.status}</span></div><h3>${p.title}</h3><p>${p.summary}</p><div class="tags">${createTags(p.skills)}</div>${v}<div class="project-links"><a class="project-detail-link" href="project.html?project=${id}">View Project Details →</a></div></article>`;}
function createProjectRow(id){const p=projects[id];const d=p.video?`<span class="row-video">▶ Demo available</span>`:"";return `<article class="project-row"><div class="row-main"><div class="project-meta"><span>${p.type}</span><span class="status">${p.status}</span></div><h3>${p.title}</h3><p>${p.summary}</p>${d}</div><div class="row-tags">${createTags(p.skills)}</div><div class="row-link"><a href="project.html?project=${id}">View Details →</a></div></article>`;}
function renderPortfolio(){const role=getCurrentRole();const p=profiles[role];document.title=`Ryan Ang | ${p.label}`;document.getElementById("role-label").textContent=p.label;document.getElementById("hero-title").textContent=p.title;document.getElementById("hero-copy").textContent=p.copy;document.getElementById("featured-note").textContent=p.note;document.getElementById("focus-skills").innerHTML=p.skills.map(s=>`<span class="skill-pill">${s}</span>`).join("");document.getElementById("featured-projects").innerHTML=p.featured.map(createProjectCard).join("");document.getElementById("all-project-list").innerHTML=p.order.map(createProjectRow).join("");}
renderPortfolio();
