const projects = {
  trading: {
    title: "Trading Journal",
    type: "Personal Project",
    status: "Offline",
    category: "Full Stack Development",
    summary: "Personal trading-journal application created to record trades and support structured trade review.",
    overview: "The Trading Journal was a personal project created to support a more structured approach to recording and reviewing trading activity. Rather than relying on spreadsheets or scattered notes, the project explored how a dedicated application could organise trading information into a repeatable review workflow.",
    goal: "The goal was to create a practical personal application for recording trading activity and reviewing previous trades while gaining experience building and operating a complete software product.",
    development: ["Designed the project as a full-stack application rather than a standalone script.","Worked with application logic and persistent data storage.","Developed functionality around recording and reviewing trading information.","Previously deployed the project as an operating application.","Evaluated the ongoing operating cost of keeping the hosted application online."],
    challenges: ["Building a personal application required making decisions beyond simply implementing features.","Data needed to be structured so that trades could be reviewed consistently.","Running the application introduced real deployment and operating costs.","The hosted version was eventually shut down because the ongoing cost was not justified for a personal project."],
    contribution: ["Designed and developed the project as a personal application.","Worked across the application's software and data layers.","Handled deployment and operation of the hosted version.","Made the decision to discontinue the hosted environment when the operating cost outweighed its value."],
    learning: ["Developed practical full-stack development experience.","Learned that deploying software introduces operational concerns beyond programming.","Improved my understanding of database-backed application design.","Learned to consider operating cost and maintainability when evaluating software architecture."],
    skills: ["Full Stack","Database Design","Deployment","Application Design","Cost Awareness"],
    source: "#", documentation: "#", video: ""
  },
  tourism: {
    title: "Tourism Web Application with NLP", type: "Academic Project", status: "Completed", category: "Full Stack · Database · NLP",
    summary: "Full-stack tourism application combining MySQL, Firestore, Node.js, Python and SpaCy-based NLP functionality.",
    overview: "This project involved developing a tourism application that connected a user-facing web application with backend services, relational and NoSQL databases and natural-language-processing functionality.",
    goal: "The goal was to move beyond designing isolated database tables and instead create an application where tourism information could be stored, retrieved, modified and presented through an integrated software system.",
    development: ["Developed application workflows connecting frontend functionality with backend services.","Worked with MySQL as the relational database component.","Worked with Firestore as a NoSQL data store.","Used JavaScript and Node.js for application and backend functionality.","Used Python for supporting application services.","Integrated SpaCy-based natural-language-processing functionality.","Worked with data retrieval and update operations across different parts of the application."],
    challenges: ["Several different technologies had to operate together as one application.","MySQL and Firestore required different approaches to organising and retrieving data.","The NLP component introduced Python into an application that also used JavaScript and Node.js.","Debugging required tracing issues across frontend, backend, database and NLP components."],
    contribution: ["Worked on application workflows connecting frontend components with backend functionality.","Worked with database operations involving MySQL and Firestore.","Used JavaScript, Node.js and Python across different components.","Integrated SpaCy-based NLP functionality."],
    learning: ["Learned how full-stack applications are separated into frontend, backend, database and supporting services.","Gained practical experience using both relational and NoSQL databases.","Improved my understanding of how database architecture affects application design.","Developed experience integrating components written using different programming languages.","Improved debugging across multi-component systems."],
    skills: ["JavaScript","Node.js","Python","MySQL","Firestore","SpaCy","Full Stack","Database Design"],
    source: "https://github.com/vaperia/school-consolidated-project/tree/main/Database/Tourism%20Webpage%20project/TourismSG-main",
    documentation: "https://github.com/vaperia/school-consolidated-project/blob/main/Database/Tourism%20Webpage%20project/Tourism%20web%20page%20guide.pdf",
    video: "https://www.youtube.com/embed/v_CCZWeDJb0"
  },
  chatbot: {
    title: "AI Chatbot", type: "Academic Project", status: "Completed", category: "Python · APIs · SQLite",
    summary: "Python chatbot application with modular application structure, SQLite persistence and external API integration.",
    overview: "The AI Chatbot project involved developing a Python application consisting of several cooperating modules rather than a single standalone script. The project combined chatbot behaviour, external API functionality, persistent storage and a graphical interface.",
    goal: "The goal was to create an interactive chatbot application that could respond to users, make use of external information sources and retain application data between sessions.",
    development: ["Developed chatbot functionality using Python.","Worked with a modular application structure.","Integrated external API functionality.","Used SQLite for persistent storage.","Worked with separate GUI, chatbot, database, settings and file-management modules.","Participated in debugging and integration of application components."],
    challenges: ["External API responses introduced behaviour outside the direct control of the local application.","Different modules needed to communicate without placing all application logic inside one script.","Persistent storage introduced additional database logic.","Debugging sometimes required identifying whether an issue originated from the GUI, application logic, API or database."],
    contribution: ["Developed Python chatbot functionality.","Worked with external API integration.","Worked with SQLite database operations.","Contributed to debugging and application integration."],
    learning: ["Learned how larger Python applications can be separated into modules.","Developed experience working with external APIs.","Learned how persistent storage affects application architecture.","Improved debugging across multiple software components.","Built a stronger foundation for later backend and full-stack development."],
    skills: ["Python","SQLite","APIs","GUI","Application Architecture","Debugging"],
    source: "https://github.com/vaperia/school-consolidated-project/tree/main/programming%20fundamental/AI%20chatbot/LAB_P11_1_Source_Code",
    documentation: "https://github.com/vaperia/school-consolidated-project/blob/main/programming%20fundamental/AI%20chatbot/LAB-P11%20-%201_Proposal.docx",
    video: "https://www.youtube.com/embed/DQ0ObN1qxto"
  },
  hobby: {
    title: "Hobby Carousel Webpage", type: "Personal Project", status: "In Progress", category: "Frontend Development",
    summary: "An in-progress personal web project focused on presenting hobbies through an interactive carousel-style interface.",
    overview: "The Hobby Carousel is an ongoing personal frontend project exploring interactive presentation, responsive layouts and user experience through a carousel-based interface.",
    goal: "The goal is to create an engaging interface where hobbies and interests can be presented and explored through a visually interactive web experience.",
    development: ["Developing the project as a personal frontend web application.","Working with JavaScript-based interaction.","Experimenting with carousel-style navigation.","Working on responsive layout behaviour.","Iterating on user-interface and user-experience decisions."],
    challenges: ["Creating a carousel interface that remains usable across different screen sizes.","Balancing visual presentation with usability.","Managing an unfinished personal project while continuing to refine its design."],
    contribution: ["Designed and developed the project independently.","Implemented frontend interaction.","Worked on responsive behaviour and interface structure."],
    learning: ["Improving practical frontend development skills.","Learning how responsive behaviour affects interactive components.","Developing a stronger understanding of interface and user-experience decisions."],
    skills: ["JavaScript","Frontend","Responsive UI","UX","Web Development"], source: "#", documentation: "#", video: ""
  },
  network: {
    title: "Smart Home Network & IoT System", type: "Academic Project", status: "Completed", category: "Computer Networks · IoT",
    summary: "Smart-home networking project covering LAN/WLAN, routing, sockets and IoT communication.",
    overview: "This project explored how different devices and services communicate in a smart-home environment. It connected networking concepts with an IoT-based system and provided an end-to-end view of device communication.",
    goal: "The goal was to understand the communication path between connected devices and services, from local connectivity through network routing and transport communication to application-level IoT behaviour.",
    development: ["Worked with LAN and WLAN networking concepts.","Applied switching and IP-addressing concepts.","Worked with packet forwarding and routing.","Applied transport-layer communication concepts.","Worked with socket-programming concepts.","Connected computer-networking concepts with IoT application communication."],
    challenges: ["The system needed to be understood as several networking layers working together.","Communication problems could originate from different layers.","The project required connecting theoretical networking concepts with the behaviour of an IoT system."],
    contribution: ["Applied networking concepts to the smart-home environment.","Worked with socket and IoT communication concepts.","Developed an end-to-end understanding of device communication."],
    learning: ["Learned how switching, routing, transport and application protocols work together.","Improved my understanding of troubleshooting communication across network layers.","Learned how networking fundamentals support IoT systems.","Developed a stronger understanding of distributed device communication."],
    skills: ["Networking","LAN","WLAN","Routing","Switching","Socket Programming","IoT"],
    source: "https://github.com/vaperia/school-consolidated-project/tree/main/computer%20network/Smart%20Home",
    documentation: "https://github.com/vaperia/school-consolidated-project/tree/main/computer%20network",
    video: "https://www.youtube.com/embed/ida8A7suqdM"
  },
  os: {
    title: "OSEK Traffic Light Project", type: "Academic Project", status: "Completed", category: "Operating Systems · OSEK",
    summary: "OSEK traffic-light control system developed and tested in a simulated operating-system environment.",
    overview: "This project involved developing and simulating a traffic-light control system using an OSEK-based operating-system environment.",
    goal: "The goal was to apply operating-system and task-based execution concepts to a control-system application instead of using only normal sequential program execution.",
    development: ["Worked with an OSEK-based project environment.","Used SimuOSEK for system simulation.","Worked with traffic-light control logic.","Tested behaviour inside the simulated environment.","Worked with project configuration together with application code.","Documented the final implementation."],
    challenges: ["Application behaviour depended on the operating-system execution model.","System testing required observing behaviour over time.","Application logic and system configuration needed to work together."],
    contribution: ["Worked with the OSEK project code and configuration.","Participated in implementation and simulation.","Contributed to system testing and documentation."],
    learning: ["Learned how operating-system behaviour affects application execution.","Developed a better understanding of task-based systems.","Improved my understanding of scheduling and timing.","Gained experience using simulation to test system behaviour."],
    skills: ["OSEK","Operating Systems","Simulation","Task Scheduling","System Behaviour"],
    source: "https://github.com/vaperia/school-consolidated-project/tree/main/Operating%20system%20project/Group14_OS_Project/OSEK-GroupProject",
    documentation: "https://github.com/vaperia/school-consolidated-project/blob/main/Operating%20system%20project/Group14_OS_Project/Operating%20System%20Group%2014%20Project%20Report.pdf",
    video: "https://www.youtube.com/embed/vEEoiYaisoI"
  },
  dsa: {
    title: "Data Structures & Algorithms Project", type: "Academic Project", status: "Completed", category: "Algorithms · Data Structures",
    summary: "INF1008 team project applying data-structure and algorithm concepts to a larger implementation.",
    overview: "This project involved applying data-structure and algorithm concepts within a team implementation and documenting the technical approach through a formal project report.",
    goal: "The goal was to translate algorithmic concepts from theory into a working software implementation.",
    development: ["Applied data-structure and algorithm concepts.","Worked within a shared team codebase.","Participated in implementation and testing.","Worked on technical project documentation."],
    challenges: ["Selecting appropriate approaches for representing information.","Ensuring components developed by team members worked together.","Maintaining implementation correctness while integrating different components."],
    contribution: ["Contributed to the team implementation.","Participated in testing and integration.","Worked on technical documentation."],
    learning: ["Improved structured reasoning around algorithms.","Learned how data representation affects software design.","Improved experience working with a shared codebase.","Developed experience explaining technical decisions through documentation."],
    skills: ["Algorithms","Data Structures","Problem Solving","Team Development"],
    source: "https://github.com/vaperia/school-consolidated-project/tree/main/data%20structure%20and%20algo/INF1008_P3_Team01",
    documentation: "https://github.com/vaperia/school-consolidated-project/blob/main/data%20structure%20and%20algo/INF1008_P3_Team01_Report.pdf",
    video: ""
  },
  embedded: {
    title: "Embedded System Smart Bin Project", type: "Academic Project", status: "Completed", category: "Embedded Systems",
    summary: "Embedded smart-bin project involving hardware/software integration, testing and system debugging.",
    overview: "The Smart Bin project was an embedded-systems group project where software logic interacted with physical system behaviour and hardware components.",
    goal: "The goal was to develop and test an embedded system where software and hardware needed to operate together reliably.",
    development: ["Worked with embedded-system source code.","Worked with system control logic.","Integrated software behaviour with physical hardware.","Performed system testing and debugging.","Worked within a group engineering project.","Documented the final system implementation."],
    challenges: ["Debugging involved observing physical system behaviour rather than only program output.","Hardware issues and software issues could influence each other.","Testing required evaluating the complete integrated system."],
    contribution: ["Contributed to embedded-system implementation.","Participated in hardware/software integration.","Worked on testing and system debugging.","Worked with the team to evaluate overall system behaviour."],
    learning: ["Developed a stronger understanding of hardware/software integration.","Learned how embedded debugging differs from ordinary software debugging.","Improved system-level troubleshooting skills.","Gained practical experience developing an embedded system as part of a team."],
    skills: ["Embedded Systems","Hardware / Software","System Integration","Debugging","System Testing"],
    source: "https://github.com/vaperia/school-consolidated-project/tree/main/embedded%20project/Group_10_Codes",
    documentation: "https://github.com/vaperia/school-consolidated-project/blob/main/embedded%20project/Group_10_report.pdf",
    video: "https://www.youtube.com/embed/Z_uJ-1ZxX9A"
  }
};
